# （1） 基本項目
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev

# (2) Deploymentのスペック
spec:
  replicas: 2   # レプリカ数
  selector:
    matchLabels:
      app: contents-vis   # テンプレートの検索条件
      tier: backend

  # (3) Podのテンプレート
  template:
    metadata:
      labels:
        app: contents-vis   # テンプレートの検索条件
        tier: backend
    spec:
      containers:
      - name: backend
        image: yuokamoto1988/contents-vis-server:v1  # コンテナイメージの場所
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000   # ポート番号

---

# (1) 基本項目
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev

# (2) Serviceのスペック
spec:
  type: LoadBalancer
  ports:   # ポート番号
    - port: 5000
      targetPort: 5000
      protocol: TCP
  
  # (3) Podの条件(ラベル)
  selector:
    app: contents-vis   # テンプレートの検索条件
    tier: backend


