# （1） 基本項目
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev

# (2) Deploymentのスペック
spec:
  replicas: 2   # レプリカ数
  selector:
    matchLabels:
      app: contents-vis   # テンプレートの検索条件
      tier: frontend

  # (3) Podのテンプレート
  template:
    metadata:
      labels:
        app: contents-vis   # テンプレートの検索条件
        tier: frontend
    spec:
      containers:
      - name: contents-vis
        image: yuokamoto1988/contents-vis-frontend:v1  # コンテナイメージの場所
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80   # ポート番号
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://20.44.132.7:5000"

---

# (1) 基本項目
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev

# (2) Serviceのスペック
spec:
  type: LoadBalancer
  ports:   # ポート番号
    - port: 80
      targetPort: 80
      protocol: TCP
  
  # (3) Podの条件(ラベル)
  selector:
    app: contents-vis   # テンプレートの検索条件
    tier: frontend

